-- ═══════════════════════════════════════════════════════════════
-- GieesK Recipes — meal_plans / meal_plan_items
-- ───────────────────────────────────────────────────────────────
-- SUPERSEDED — no action needed.
--
-- These tables already exist in your database from the original
-- Shapem setup script, as a two-table structure:
--   meal_plans:      id, user_id, name, start_date, end_date
--   meal_plan_items: id, plan_id (FK), recipe_id, day_of_week (0-6),
--                    meal_type, servings
--
-- My first version of this file assumed a single flat table with
-- different columns entirely. The code has been rewritten to match
-- the real two-table structure above — you do NOT need to run any
-- SQL for this. If you already ran the old version of this file,
-- it's harmless: it only added a few unused extra columns to
-- meal_plans, nothing was broken or lost.
--
-- One assumption worth double-checking: day_of_week is stored as
-- 0=Sunday..6=Saturday (JavaScript's native Date.getDay() convention).
-- If your original app used a different mapping, let me know and
-- I'll adjust.
