-- ═══════════════════════════════════════════════════════════════
-- GieesK Recipes — shopping_list_items
-- ───────────────────────────────────────────────────────────────
-- SUPERSEDED — no action needed.
--
-- This table already exists in your database from the original
-- Shapem setup script, with this real structure:
--   id (bigserial), user_id, ingredient, amount, checked,
--   recipe_id, created_at
--
-- My first version of this file assumed different column names
-- (name/category/recipe_title) that don't match. The code has been
-- corrected to use the real columns above — you do NOT need to run
-- any SQL for this table. If you already ran the old version of
-- this file, it's harmless: it only added a few unused extra
-- columns alongside the real ones, nothing was broken or lost.
