/* ═══════════════════════════════════════════
   SHAPEM — Data Layer
═══════════════════════════════════════════ */
const RECIPES = [

  // ── 🌍 WORLD FEATURED ────────────────────────────────────────────────────
  { id:1,  title:'Saffron Lamb Tagine',  emoji:'🍲', country:'Morocco',  countryFlag:'🇲🇦', cuisine:'Moroccan',       time:90,  prepTime:15, cookTime:75, servings:4, diff:'Medium', cal:520, rating:4.9, reviews:312,  tags:['halal','gluten-free'],        author:'Fatima El-Amin',  authorEmoji:'👩🏽‍🍳', desc:'Slow-braised lamb with saffron, preserved lemon, olives, and a mountain of warming spices. Serve over fluffy couscous.', ingredients:['1.2kg bone-in lamb shoulder','2 tbsp saffron water','1 preserved lemon','200g green olives','3 onions','4 garlic cloves','1 tbsp ras el hanout','2 tbsp honey','Fresh coriander','Couscous to serve'], steps:['Season lamb generously with salt and ras el hanout.','Sear in a large tagine or heavy casserole until browned all over.','Add sliced onions and garlic; cook until softened.','Pour in saffron water, 300ml stock, and honey. Tuck in preserved lemon.','Cover and simmer on low for 1.5 hours until lamb falls off the bone.','Add olives for the final 15 minutes. Garnish with fresh coriander.'], nutrition:{cal:520,protein:38,carbs:22,fat:28} },
  { id:2,  title:'Truffle Carbonara',    emoji:'🍝', country:'Italy',    countryFlag:'🇮🇹', cuisine:'Italian',        time:25,  prepTime:5,  cookTime:20, servings:4, diff:'Easy',   cal:680, rating:4.8, reviews:528,  tags:['vegetarian'],                 author:'Marco Bellini',   authorEmoji:'👨🏻‍🍳', desc:'Roman classic elevated with black truffle. Silky egg and pecorino sauce, no cream ever. A lesson in restraint.', ingredients:['400g spaghetti','200g guanciale','4 egg yolks','1 whole egg','100g pecorino romano','Black truffle shavings','Freshly cracked black pepper','Salt'], steps:['Cook pasta in well-salted boiling water until al dente.','Render guanciale in a cold pan until crispy. Remove from heat.','Whisk egg yolks, whole egg, and pecorino with plenty of black pepper.','Reserve 1 cup pasta water. Drain pasta and add to pan with guanciale.','Off heat, pour egg mixture over pasta. Toss vigorously, adding pasta water to achieve silky sauce.','Finish with truffle shavings and extra pecorino.'], nutrition:{cal:680,protein:28,carbs:72,fat:30} },
  { id:3,  title:'Miso Black Cod',       emoji:'🐟', country:'Japan',    countryFlag:'🇯🇵', cuisine:'Japanese',       time:30,  prepTime:10, cookTime:20, servings:4, diff:'Medium', cal:410, rating:4.9, reviews:441,  tags:['gluten-free','pescatarian'],  author:'Yuki Tanaka',     authorEmoji:'👩🏻‍🍳', desc:'Nobu-inspired miso-marinated black cod. Silky, lacquered, impossibly tender. Marinate 2–3 days for best results.', ingredients:['4 black cod fillets','200ml white miso paste','150ml mirin','150ml sake','100g sugar','Pickled ginger to serve','Micro shiso leaves'], steps:['Whisk miso, mirin, sake, and sugar in a saucepan over medium heat until sugar dissolves. Cool completely.','Pat cod dry and coat generously in marinade. Cover and refrigerate 2–3 days.','Scrape off excess marinade. Broil at high heat for 8–10 minutes until caramelised.','Serve immediately with pickled ginger and micro shiso.'], nutrition:{cal:410,protein:36,carbs:28,fat:14} },
  { id:4,  title:'Birria Tacos',         emoji:'🌮', country:'Mexico',   countryFlag:'🇲🇽', cuisine:'Mexican',        time:180, prepTime:20, cookTime:160,servings:6, diff:'Hard',   cal:490, rating:4.8, reviews:389,  tags:['halal'],                      author:'Carlos Reyes',    authorEmoji:'👨🏽‍🍳', desc:'Juicy braised beef birria with rich consommé for dipping. Crispy, cheesy, deeply spiced. Weekend project, weekday reward.', ingredients:['1.5kg beef chuck','4 dried guajillo chillies','2 ancho chillies','4 chipotle in adobo','1 white onion','6 garlic cloves','1 tsp cumin','1 tsp Mexican oregano','Corn tortillas','Oaxaca cheese','White onion & coriander to serve'], steps:['Toast and rehydrate dried chillies. Blend with onion, garlic, chipotles, and spices into a smooth paste.','Marinate beef in the paste overnight.','Brown beef in a heavy pot. Add remaining marinade and 1L water. Simmer covered for 3 hours until shreddable.','Shred beef and strain braising liquid into a bowl (this is the consommé).','Dip tortillas in consommé, fill with beef and cheese, fold and fry in a hot skillet until crispy.','Serve with a bowl of hot consommé for dipping.'], nutrition:{cal:490,protein:34,carbs:36,fat:22} },
  { id:5,  title:'Butter Chicken',       emoji:'🍛', country:'India',    countryFlag:'🇮🇳', cuisine:'Indian',         time:50,  prepTime:15, cookTime:35, servings:4, diff:'Easy',   cal:560, rating:4.7, reviews:614,  tags:['gluten-free','halal'],        author:'Priya Sharma',    authorEmoji:'👩🏾‍🍳', desc:'The definitive butter chicken: charred tandoori-style chicken in a velvety, mildly spiced tomato-cream sauce. Goes with everything.', ingredients:['800g chicken thighs','2 tbsp tandoori paste','150ml yoghurt','400g canned tomatoes','150ml double cream','3 tbsp ghee','2 onions','4 garlic cloves','1 tbsp fresh ginger','1 tsp garam masala','1 tsp kashmiri chilli'], steps:['Marinate chicken in yoghurt and tandoori paste for at least 2 hours.','Grill or broil chicken until charred at edges. Set aside.','Fry onions in ghee until deep golden. Add garlic, ginger, and spices.','Add tomatoes; simmer 15 minutes. Blend sauce until smooth.','Return to pan, add cream and chicken. Simmer 10 minutes.','Season to taste. Finish with a knob of butter and fresh coriander.'], nutrition:{cal:560,protein:40,carbs:18,fat:32} },
  { id:6,  title:'Shakshuka',            emoji:'🍳', country:'Israel',   countryFlag:'🇮🇱', cuisine:'Middle Eastern', time:25,  prepTime:5,  cookTime:20, servings:4, diff:'Easy',   cal:320, rating:4.7, reviews:487,  tags:['vegetarian','vegan-opt'],     author:'Layla Nasser',    authorEmoji:'👩🏽‍🍳', desc:'Spiced tomato sauce with perfectly set eggs, feta, and fresh herbs. Weekend breakfast turned weeknight dinner.', ingredients:['6 eggs','800g canned tomatoes','1 red pepper','1 onion','4 garlic cloves','1 tsp cumin','1 tsp smoked paprika','½ tsp cayenne','100g feta cheese','Fresh parsley','Good bread to serve'], steps:['Sauté onion and pepper until soft. Add garlic and spices; cook 1 minute.','Pour in tomatoes; simmer 10 minutes until thickened. Season well.','Create 6 wells in the sauce. Crack an egg into each.','Cover and cook on low until whites are set but yolks still runny (5–7 min).','Crumble feta over the top. Scatter fresh parsley. Serve from pan with crusty bread.'], nutrition:{cal:320,protein:20,carbs:22,fat:16} },
  { id:7,  title:'Pad Thai',             emoji:'🍜', country:'Thailand', countryFlag:'🇹🇭', cuisine:'Thai',           time:20,  prepTime:10, cookTime:10, servings:2, diff:'Easy',   cal:510, rating:4.6, reviews:392,  tags:['vegan-opt'],                  author:'Nong Krai',       authorEmoji:'👨🏻‍🍳', desc:'Street-style pad thai: chewy rice noodles, wok-charred shrimp, tamarind sauce, crunchy peanuts. 20 minutes start to finish.', ingredients:['200g flat rice noodles','300g shrimp','3 tbsp tamarind paste','2 tbsp fish sauce','1 tbsp sugar','2 eggs','3 spring onions','100g bean sprouts','50g crushed peanuts','Lime to serve','Red chilli'], steps:['Soak noodles in warm water 20 minutes until pliable. Drain.','Mix tamarind, fish sauce, and sugar into a sauce.','Heat wok until smoking. Stir-fry shrimp until pink. Push to side.','Add noodles and sauce. Toss over high heat.','Push to side, scramble eggs. Mix everything together.','Add sprouts and spring onions. Plate and top with peanuts, lime, chilli.'], nutrition:{cal:510,protein:28,carbs:62,fat:16} },
  { id:8,  title:'Beef Wellington',      emoji:'🥩', country:'UK',       countryFlag:'🇬🇧', cuisine:'British',        time:120, prepTime:30, cookTime:90, servings:6, diff:'Expert', cal:740, rating:4.9, reviews:218,  tags:['special-occasion'],           author:'James Whitfield', authorEmoji:'👨🏼‍🍳', desc:'Gordon Ramsay would approve. Beef fillet wrapped in mushroom duxelles and golden puff pastry. The showstopper of showstoppers.', ingredients:['1kg beef fillet','500g chestnut mushrooms','6 slices prosciutto','500g puff pastry','2 egg yolks','2 tbsp Dijon mustard','1 tbsp thyme','Truffle oil optional'], steps:['Sear beef fillet all over until browned. Brush with Dijon. Chill.','Blitz mushrooms; cook in butter until all moisture evaporates. Season. Cool.','Lay prosciutto on clingfilm, spread duxelles, roll beef tightly. Refrigerate 30 min.','Wrap in puff pastry, seal edges, brush with egg wash. Score top decoratively.','Bake at 220°C for 25–28 minutes until pastry is deep golden.','Rest 10 minutes before slicing to serve.'], nutrition:{cal:740,protein:52,carbs:38,fat:42} },

  // ── 🇰🇪 KENYA ─────────────────────────────────────────────────────────────

  {
    id: 'KEN003',
    title: 'Kenyan Beef Stew',
    localName: 'Beef Stew',
    emoji: '🧆',
    country: 'Kenya',
    countryFlag: '🇰🇪',
    region: 'East Africa',
    community: 'National',
    cuisine: 'Kenyan',
    category: 'Meat Dish',
    course: 'Main Course',
    diff: 'Easy',
    prepTime: 20,
    cookTime: 90,
    time: 110,
    servings: 6,
    cal: 365,
    rating: 4.9,
    reviews: 2341,
    tags: ['gluten-free', 'dairy-free', 'nut-free', 'halal'],
    author: 'Mama Wanjiru',
    authorEmoji: '👩🏿‍🍳',
    desc: "Kenyan Beef Stew is the ultimate comfort dish — tender beef slow-simmered in a rich tomato gravy with onions, garlic, ginger, and warm spices. Found on nearly every Kenyan family table, it is the perfect companion to ugali, chapati, or rice.",
    longDesc: "Every Kenyan home has its version of beef stew, and every version tells a story. The secret is patience — browning the beef first for deep caramelised flavour, then simmering low and slow until the meat practically falls apart in the gravy. Prepared for Sunday lunches, celebrations, and ordinary weekday dinners alike, this is the dish that makes a house smell like home.",
    ingredients: [
      '1 kg stewing beef — cut into 3–4 cm cubes',
      '2 large onions (300g) — finely chopped',
      '4 medium tomatoes (500g) — chopped',
      '4 garlic cloves — minced',
      '1 tbsp fresh ginger — grated',
      '2 tbsp tomato paste — optional but recommended',
      '3 tbsp vegetable or sunflower oil',
      '3 cups (720ml) beef stock or water',
      '2 medium carrots — sliced',
      '1 green bell pepper — chopped (optional)',
      '2 tsp salt — adjust to taste',
      '1 tsp freshly ground black pepper',
      '1 tsp curry powder — optional',
      '2 tbsp fresh coriander — chopped, for garnish',
    ],
    equipment: ['Heavy-bottomed sufuria or Dutch oven', 'Wooden spoon', 'Knife', 'Chopping board', 'Measuring cups and spoons'],
    steps: [
      'Wash the beef, pat it completely dry with a cloth, and season lightly with salt and black pepper.',
      'Heat the oil in a heavy sufuria over medium-high heat until shimmering.',
      'Brown the beef in batches — do not crowd the pot. Sear each batch until deeply caramelised on all sides, then remove and set aside. This step builds the entire foundation of flavour.',
      'In the same pot, add the onions and cook over medium heat until deeply golden, about 8 minutes.',
      'Add the garlic and ginger, stirring for 1 minute until fragrant.',
      'Stir in the chopped tomatoes and tomato paste. Cook, stirring occasionally, until the tomatoes completely break down into a thick, dark sauce — about 10 minutes.',
      'Return the browned beef to the pot, stirring to coat every piece in the tomato base.',
      'Pour in the beef stock and bring to a gentle boil.',
      'Reduce heat to low, cover, and simmer for 60–75 minutes, stirring occasionally, until the beef is nearly tender.',
      'Add the carrots and bell pepper during the last 20 minutes of cooking.',
      'Continue simmering uncovered for the final 10 minutes to thicken the gravy to your liking.',
      'Taste and adjust seasoning. Garnish generously with fresh coriander and serve hot.',
    ],
    chefTips: [
      'Use beef with some marbling — chuck or shin cuts give the richest, most tender result.',
      'Never skip the browning step — it adds a depth of flavour you simply cannot get any other way.',
      'Simmer gently, never boil rapidly — a rolling boil will toughen the beef.',
      'Make it the day before — beef stew always tastes even better the next day as the flavours deepen overnight.',
    ],
    commonMistakes: [
      'Cooking on high heat throughout — makes the beef tough and dry.',
      'Skipping the browning step — results in a flat, grey stew without depth.',
      'Adding all vegetables at the start — carrots and peppers will turn to mush.',
      'Too little liquid — causes the bottom to scorch before the beef is tender.',
    ],
    servedWith: ['White Ugali', 'Sukuma Wiki', 'Brown Ugali', 'Chapati', 'Rice', 'Mukimo', 'Mashed Potatoes', 'Steamed Green Vegetables'],
    relatedRecipes: ['KEN001', 'KEN002', 'KEN004'],
    storage: 'Refrigerate in an airtight container for up to 4 days. Freeze for up to 3 months.',
    reheating: 'Reheat gently on the stovetop over low heat, adding a splash of water or stock if the sauce has thickened. Alternatively microwave in short intervals, stirring between each.',
    healthBenefits: [
      'Excellent source of high-quality protein — 32g per serving.',
      'Rich in iron — supports healthy red blood cells and energy levels.',
      'Provides zinc for immune function and wound healing.',
      'Contains vitamin B12, essential for nerve health and energy metabolism.',
      'Forms a balanced, complete meal when served with ugali and leafy greens.',
    ],
    culturalNote: "Beef stew is a cornerstone of Kenyan family cooking — prepared for Sunday lunches, celebrations, and ordinary weekday dinners. While every household has its own recipe, the combination of beef, onions, tomatoes, and slow cooking is deeply familiar across all communities. It is considered the ultimate Kenyan comfort food.",
    regionalVariations: [
      'Coastal version — cooked with coconut milk and mild spices for a creamier, fragrant gravy.',
      'Central Kenyan version — traditionally served alongside mukimo.',
      'Western Kenyan version — extra tomatoes and green peppers, deeply sauced.',
      'Northern Kenyan variation — spiced with cumin and coriander seeds.',
      'Modern version — with mushrooms or peas added for extra texture.',
    ],
    nutrition: { cal: 365, protein: 32, carbs: 10, fat: 22, fiber: 2, sodium: 620 },
    keywords: ['kenyan beef stew', 'african beef stew', 'east african cuisine', 'tomato beef stew', 'ugali companion', 'kenyan comfort food'],
  },


  {
    id: 'KEN004',
    title: 'Kenyan Layered Chapati',
    localName: 'Chapati',
    emoji: '🦿',
    country: 'Kenya',
    countryFlag: '🇰🇪',
    region: 'East Africa',
    community: 'National',
    cuisine: 'Kenyan',
    category: 'Flatbread',
    course: 'Main Dish / Side Dish / Breakfast',
    diff: 'Medium',
    prepTime: 25,
    cookTime: 20,
    restTime: 30,
    time: 75,
    servings: 10,
    yieldDesc: '10 chapatis (approximately 25 cm each)',
    cal: 280,
    rating: 4.9,
    reviews: 3102,
    tags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free'],
    author: 'Mama Wanjiru',
    authorEmoji: '👩🏿‍🍳',
    desc: "Kenyan Chapati is a soft, flaky, pan-cooked flatbread beloved across the country. Its signature delicate layers come from a simple technique of rolling, oiling, folding, and coiling the dough before cooking. Served at breakfast, celebrations, and everyday meals, chapati is one of Kenya's most treasured breads.",
    longDesc: "Few things in a Kenyan kitchen bring as much satisfaction as a perfectly layered chapati — golden on the outside, soft and flaky within. The technique of coiling the dough before re-rolling is the heart of it, trapping thin layers of oil between sheets of dough that separate beautifully during cooking. Chapati carries the gentle influence of South Asian cuisine woven into Kenyan food culture over generations, and today it appears on tables from the coast to the highlands, at weddings, Christmas, Eid, and quiet Sunday mornings alike.",
    ingredients: [
      '1 kg all-purpose flour — sifted',
      '550–600 ml warm water — add gradually',
      '2 tsp salt',
      '1 tbsp sugar — optional, for light golden browning',
      '6 tbsp vegetable oil — for the dough',
      '5 tbsp vegetable oil — for layering and frying',
    ],
    equipment: ['Large mixing bowl', 'Rolling pin', 'Frying pan (tawa)', 'Pastry brush or spoon', 'Clean kitchen towel', 'Measuring cups and spoons'],
    steps: [
      'Combine the flour, salt, and optional sugar in a large bowl. Add the 6 tbsp of oil and mix until it is evenly distributed and the flour feels slightly crumbly.',
      'Gradually pour in the warm water while mixing, bringing the dough together until it is soft, smooth, and not sticky. Add water slowly — you may not need all of it.',
      'Knead the dough firmly for 10–12 minutes until it becomes smooth, elastic, and springs back when poked.',
      'Cover with a damp cloth and rest for 30 minutes. This step is essential — do not skip it.',
      'Divide the rested dough into 10 equal balls.',
      'Roll one ball into a thin circle about 25 cm wide using a lightly oiled surface.',
      'Lightly brush the surface of the circle with oil.',
      'Fold or roll into a long strip, then coil it tightly into a spiral like a snail shell. Pinch the end underneath to seal.',
      'Let the coiled dough rest for 5–10 minutes, then gently roll it back into a round chapati — the layers will stay intact inside.',
      'Heat a dry frying pan (tawa) over medium heat until hot.',
      'Place the chapati on the dry pan and cook for about 1 minute until bubbles start to form.',
      'Flip and brush the cooked side lightly with oil. Flip again, oil the second side, and continue turning until both sides are evenly golden with visible flaky spots — about 3–4 minutes total.',
      'Remove from the pan while hot and gently clap between your hands or squeeze with a clean towel to separate the beautiful flaky layers.',
      'Repeat with remaining dough, keeping finished chapatis covered to stay warm and soft.',
    ],
    chefTips: [
      'Resting the dough is non-negotiable — it relaxes the gluten and makes rolling much easier.',
      'Use warm water, not cold — it produces a more elastic, pliable dough.',
      'Go easy on flour when rolling — too much dries out the chapati. Use a lightly oiled surface instead.',
      'Cook over medium heat always — high heat burns the outside before the inside cooks through.',
      'Clapping the chapati while still hot separates the layers dramatically. Do not skip this step.',
    ],
    commonMistakes: [
      'Skipping the resting period — the dough will resist rolling and tear.',
      'Using cold water — produces a stiff, less pliable dough.',
      'Rolling the dough too thick — results in dense, doughy chapatis.',
      'Cooking on high heat — the outside burns while the inside stays raw.',
      'Over-oiling — makes the chapatis greasy and heavy.',
    ],
    servedWith: ['Kenyan Beef Stew', 'Chicken Stew', 'Goat Stew', 'Maharagwe (Bean Stew)', 'Ndengu (Green Gram)', 'Sukuma Wiki', 'Vegetable Curry', 'Chai ya Maziwa'],
    relatedRecipes: ['KEN001', 'KEN002', 'KEN003'],
    storage: 'Room temperature in an airtight container for up to 2 days. Refrigerate for up to 5 days. Freeze for up to 2 months — separate each chapati with parchment paper.',
    reheating: 'Warm on a dry frying pan for 1–2 minutes per side, or microwave briefly under a damp paper towel to restore softness.',
    healthBenefits: [
      'Provides complex carbohydrates for sustained energy throughout the day.',
      'Offers moderate protein (6g per chapati) from wheat flour.',
      'Can be made with whole-wheat flour to significantly increase fibre content.',
      'Pairs beautifully with vegetables and protein-rich stews for a complete, balanced meal.',
    ],
    culturalNote: "Chapati is one of Kenya's most treasured breads, reflecting the enduring influence of South Asian cuisine woven into Kenyan food culture over many generations. Today it is prepared for festive occasions, family gatherings, and ordinary meals in homes across every community. Many families pass down their own techniques — particularly the art of creating those perfect flaky layers — from mother to daughter.",
    regionalVariations: [
      'Whole-wheat chapati — nuttier flavour and higher fibre.',
      'Coconut chapati — popular along the Kenyan coast, rich and fragrant.',
      'Pumpkin chapati — golden colour, slightly sweet.',
      'Beetroot chapati — vibrant pink, earthy flavour.',
      'Herb and garlic chapati — modern urban variation.',
      'Luxury layered chapati — extra folds for maximum flakiness.',
    ],
    nutrition: { cal: 280, protein: 6, carbs: 42, fat: 10, fiber: 2, sodium: 230 },
    keywords: ['kenyan chapati', 'layered chapati', 'east african flatbread', 'homemade chapati', 'flaky chapati', 'soft chapati', 'african bread'],
  },

  {
    id: 'KEN001',
    title: 'White Ugali',
    localName: 'Ugali',
    emoji: '🫓',
    country: 'Kenya',
    countryFlag: '🇰🇪',
    region: 'East Africa',
    community: 'National',
    cuisine: 'Kenyan',
    category: 'Staple Food',
    course: 'Main Dish',
    diff: 'Easy',
    prepTime: 2,
    cookTime: 15,
    time: 17,
    servings: 4,
    cal: 210,
    rating: 4.8,
    reviews: 1240,
    tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    author: 'Mama Wanjiru',
    authorEmoji: '👩🏿‍🍳',
    desc: "White Ugali is Kenya's most iconic staple — just two ingredients, maize flour and water, transformed by fire and patience into something deeply nourishing. Firm, smooth, and subtly earthy, it is the canvas on which Kenyan cuisine is painted.",
    longDesc: "More than a meal, Ugali is a cultural cornerstone eaten across nearly every Kenyan community. The technique is deceptively simple — water, flour, heat, and a wooden mwiko — yet mastering the stir, knowing when it pulls from the sides, and getting the dome just right is a skill passed from mother to child across generations.",
    ingredients: [
      '4 cups (960 ml) clean drinking water',
      '2 cups (300 g) white maize flour — freshly milled for best flavour',
    ],
    equipment: ['Medium cooking pot', 'Wooden cooking stick (mwiko)', 'Measuring cups', 'Serving plate'],
    steps: [
      'Pour the water into a medium pot and bring to a rolling boil over medium-high heat.',
      'Sprinkle in a small handful of maize flour while stirring to form a thin, lump-free slurry — this is the secret to a smooth ugali.',
      'Gradually add the remaining maize flour in small batches, stirring vigorously and continuously with a mwiko to prevent lumps.',
      'Keep stirring as the mixture thickens and begins to pull away cleanly from the sides of the pot.',
      'Reduce the heat to low and cook for a further 2–3 minutes, pressing and folding the ugali firmly against the pot walls.',
      'Fold and press with the mwiko until the ugali is completely smooth, glossy, and holds its shape.',
      'Wet the inside of the pot or a serving plate with a little water, then turn the ugali out and shape into a neat dome.',
      'Serve immediately while hot alongside your favourite stew, greens, or grilled meat.',
    ],
    chefTips: [
      'Use freshly milled maize flour — older flour can taste stale and affects the smooth finish.',
      'Never add all the flour at once. Gradual addition is the key to a lump-free ugali.',
      'Keep stirring throughout — stopping even briefly can cause the base to scorch.',
      'Adjust flour quantity slightly: more for firmer ugali (western Kenya style), slightly less for a softer result (coastal preference).',
    ],
    commonMistakes: [
      'Adding all the flour at once — creates lumps that are nearly impossible to remove.',
      'Cooking on very high heat after thickening — scorches the base without cooking the inside.',
      'Using old or poorly milled maize flour — compromises flavour and texture.',
    ],
    servedWith: ['Sukuma Wiki', 'Beef Stew', 'Nyama Choma', 'Goat Stew', 'Fried Tilapia', 'Omena Stew', 'Chicken Stew', 'Managu', 'Terere', 'Mrenda'],
    relatedRecipes: ['KEN002', 'KEN003', 'KEN004'],
    storage: 'Refrigerate in an airtight container for up to 3 days. Freeze for up to 1 month.',
    reheating: 'Steam or microwave with a few drops of water until heated through.',
    healthBenefits: [
      'Excellent source of complex carbohydrates for sustained energy.',
      'Naturally low in fat — just 1g per serving.',
      'Gluten-free when made with pure maize flour.',
      'Pairs perfectly with protein- and vegetable-rich dishes to create a balanced, complete meal.',
    ],
    culturalNote: "Ugali is the heart of Kenyan cuisine, eaten in homes, restaurants, schools, and celebrations from coast to highlands. It is traditionally eaten with the right hand — a small piece pinched off, rolled into a ball, and used to scoop stew or greens. Sharing ugali from one plate is an act of togetherness.",
    regionalVariations: [
      'Softer ugali — preferred in some coastal communities.',
      'Firmer ugali — common in western Kenya.',
      'Brown ugali — made with whole-maize flour, nuttier in flavour.',
      'Millet ugali (Ugali wa Wimbi) — darker, slightly sour, rich in iron.',
      'Sorghum ugali — common in arid regions, deep earthy flavour.',
      'Mixed-grain ugali — blend of maize, millet, and sorghum.',
    ],
    nutrition: { cal: 210, protein: 4, carbs: 46, fat: 1, fiber: 2, sodium: 5 },
    keywords: ['ugali', 'kenyan food', 'maize meal', 'cornmeal', 'african staple', 'east african', 'gluten-free', 'vegan'],
  },

  {
    id: 'KEN002',
    title: 'Sukuma Wiki',
    localName: 'Sukuma Wiki',
    emoji: '🥬',
    country: 'Kenya',
    countryFlag: '🇰🇪',
    region: 'East Africa',
    community: 'National',
    cuisine: 'Kenyan',
    category: 'Vegetable Dish',
    course: 'Side Dish',
    diff: 'Easy',
    prepTime: 10,
    cookTime: 12,
    time: 22,
    servings: 4,
    cal: 95,
    rating: 4.8,
    reviews: 1876,
    tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    author: 'Mama Wanjiru',
    authorEmoji: '👩🏿‍🍳',
    desc: 'Sukuma Wiki — Swahili for "push the week" — is Kenya\'s most beloved everyday vegetable dish. Collard greens wilted with tomatoes, onion, and garlic into a bright, flavourful side that stretches any meal further without sacrificing nutrition or taste.',
    longDesc: "You'll find Sukuma Wiki simmering on nearly every stove in Kenya — from Nairobi apartments to rural homesteads, from roadside mama mbogas to city restaurants. When piled beside a dome of steaming white ugali and scooped up by hand, it becomes something greater than the sum of its humble ingredients.",
    ingredients: [
      '500g sukuma wiki (collard greens) — washed and thinly sliced',
      '1 medium onion (120g) — finely chopped',
      '2 medium tomatoes (200g) — diced',
      '2 garlic cloves — minced',
      '2 tbsp vegetable or sunflower oil',
      '1 tsp salt — adjust to taste',
      '¼ tsp black pepper — optional',
      '1 tsp Royco or beef seasoning — optional',
      '¼ cup (60ml) water — if needed during cooking',
    ],
    equipment: ['Frying pan or sufuria', 'Wooden spoon', 'Knife', 'Chopping board', 'Measuring spoons'],
    steps: [
      'Wash the sukuma wiki thoroughly under running water, inspecting each leaf carefully.',
      'Remove any tough central stems if desired, then stack the leaves and slice into thin, even strips.',
      'Heat the oil in a sufuria or frying pan over medium heat until shimmering.',
      'Add the chopped onion and cook for 3–4 minutes, stirring, until soft and translucent.',
      'Stir in the minced garlic and cook for about 30 seconds until fragrant — don\'t let it brown.',
      'Add the diced tomatoes and cook for 3–4 minutes until they break down into a light sauce.',
      'Season with salt, black pepper, and Royco if using.',
      'Add the sliced sukuma wiki in batches, stirring continuously as each addition wilts down.',
      'If the pan looks dry, add a small splash of water to keep things moving.',
      'Cook for 5–7 minutes until tender but still vibrantly green.',
      'Taste, adjust seasoning, and serve immediately alongside ugali.',
    ],
    chefTips: [
      "Don't overcook — the greens should stay vibrant and have a gentle bite. Dull, khaki-green sukuma wiki is overcooked.",
      'Young, fresh leaves are sweeter and more tender. Avoid yellowing or wilted bunches.',
      'A small knob of butter stirred in at the very end adds richness without overwhelming the greens.',
      'For extra protein, stir in cooked kidney beans or a few scrambled eggs just before serving.',
    ],
    commonMistakes: [
      'Overcooking — the greens lose their colour, nutrients, and texture completely.',
      'Too much water — the dish becomes watery and loses its concentrated flavour.',
      'Skipping the tomatoes — they provide balance, moisture, and a gentle acidity that lifts the dish.',
      'Cooking on high heat — scorches the onion and garlic before the tomatoes have time to soften.',
    ],
    servedWith: ['White Ugali', 'Brown Ugali', 'Beef Stew', 'Nyama Choma', 'Fried Tilapia', 'Goat Stew', 'Chapati', 'Rice', 'Githeri'],
    relatedRecipes: ['KEN001', 'KEN003', 'KEN004'],
    storage: 'Refrigerate in an airtight container for up to 3 days. Freezing not recommended — texture becomes soft after thawing.',
    reheating: 'Reheat gently in a pan over medium heat with a teaspoon of water, or microwave until warmed through.',
    healthBenefits: [
      'Rich in vitamins A, C, and K — supports immunity, vision, and bone health.',
      'Excellent source of dietary fibre — promotes healthy digestion.',
      'Contains iron and calcium — essential for energy and strong bones.',
      'Naturally low in calories (95 kcal per serving) while delivering valuable micronutrients.',
    ],
    culturalNote: 'Sukuma Wiki appears on menus from roadside mama mbogas to family restaurants across Kenya. Its Swahili name — "push the week" — reflects how it has helped generations of Kenyan families eat nutritiously on a budget.',
    regionalVariations: [
      'Coastal version — cooked with coconut milk for a richer, slightly sweet flavour.',
      'Western Kenyan version — onions and a splash of fresh milk stirred in at the end.',
      'Central Kenyan version — served alongside irio or mukimo.',
      'Modern urban version — with carrots and colourful bell peppers added.',
      'Protein-rich variation — minced beef or scrambled eggs stirred through.',
    ],
    nutrition: { cal: 95, protein: 3, carbs: 9, fat: 6, fiber: 4, sodium: 380 },
    keywords: ['sukuma wiki', 'collard greens', 'kenyan vegetables', 'east african food', 'healthy side dish'],
  },

];

// ── Country registry (auto-built + manual overrides) ──────────────────────
const COUNTRY_REGISTRY = {};
RECIPES.forEach(r => {
  if (!r.country) return;
  if (!COUNTRY_REGISTRY[r.country]) {
    COUNTRY_REGISTRY[r.country] = { flag: r.countryFlag || '', count: 0, region: r.region || '' };
  }
  COUNTRY_REGISTRY[r.country].count++;
});

const CUISINES = [
  { name:'Italian',       flag:'🇮🇹', count:3240, color:'#8B1A1A' },
  { name:'Japanese',      flag:'🇯🇵', count:2810, color:'#BC002D' },
  { name:'Mexican',       flag:'🇲🇽', count:2190, color:'#006847' },
  { name:'Indian',        flag:'🇮🇳', count:3650, color:'#FF9933' },
  { name:'Thai',          flag:'🇹🇭', count:1840, color:'#00247D' },
  { name:'Moroccan',      flag:'🇲🇦', count:980,  color:'#C1272D' },
  { name:'French',        flag:'🇫🇷', count:2450, color:'#002395' },
  { name:'Lebanese',      flag:'🇱🇧', count:1120, color:'#00A651' },
  { name:'Chinese',       flag:'🇨🇳', count:4100, color:'#DE2910' },
  { name:'Greek',         flag:'🇬🇷', count:1360, color:'#0D5EAF' },
  { name:'Ethiopian',     flag:'🇪🇹', count:620,  color:'#FCDD09' },
  { name:'Peruvian',      flag:'🇵🇪', count:810,  color:'#D91023' },
  { name:'Kenyan',        flag:'🇰🇪', count:4,    color:'#006600' },
];

const CHEFS = [
  { name:'Fatima El-Amin', origin:'Marrakech, Morocco', emoji:'👩🏽‍🍳', recipes:142, followers:48200,  rating:4.9, specialty:'North African' },
  { name:'Marco Bellini',  origin:'Rome, Italy',        emoji:'👨🏻‍🍳', recipes:218, followers:92100,  rating:4.8, specialty:'Italian Classics' },
  { name:'Yuki Tanaka',    origin:'Tokyo, Japan',       emoji:'👩🏻‍🍳', recipes:189, followers:67400,  rating:4.9, specialty:'Japanese Fusion' },
  { name:'Priya Sharma',   origin:'Mumbai, India',      emoji:'👩🏾‍🍳', recipes:231, followers:115000, rating:4.7, specialty:'Indian Regional' },
  { name:'Carlos Reyes',   origin:'Oaxaca, Mexico',     emoji:'👨🏽‍🍳', recipes:167, followers:54300,  rating:4.8, specialty:'Mexican Street Food' },
  { name:'James Whitfield',origin:'London, UK',         emoji:'👨🏼‍🍳', recipes:94,  followers:38900,  rating:4.9, specialty:'Classical French' },
  { name:'Layla Nasser',   origin:'Beirut, Lebanon',    emoji:'👩🏽‍🍳', recipes:158, followers:43700,  rating:4.7, specialty:'Levantine' },
  { name:'Nong Krai',      origin:'Bangkok, Thailand',  emoji:'👨🏻‍🍳', recipes:203, followers:71200,  rating:4.6, specialty:'Thai Street Food' },
  { name:'Mama Wanjiru',   origin:'Nairobi, Kenya',     emoji:'👩🏿‍🍳', recipes:24,  followers:18600,  rating:4.8, specialty:'Kenyan Traditional' },
];

const BADGES = [
  { icon:'🔥', title:'Hot Streak',    desc:'Cook 7 days in a row' },
  { icon:'⭐', title:'5-Star Chef',    desc:'Receive 100 five-star reviews' },
  { icon:'🌍', title:'World Traveler', desc:'Cook from 20 different cuisines' },
  { icon:'⚡', title:'Speed Cook',     desc:'Complete 50 quick recipes' },
  { icon:'🌱', title:'Plant Power',    desc:'Cook 30 vegan meals' },
  { icon:'🏆', title:'Champion',       desc:'Win a weekly challenge' },
  { icon:'📖', title:'Storyteller',    desc:'Write 10 detailed recipe stories' },
  { icon:'🎯', title:'Precision',      desc:'Follow 100 recipes exactly' },
];

const LEADERBOARD = [
  { rank:1, name:'Chef Marco',  emoji:'👨🏻‍🍳', score:98420 },
  { rank:2, name:'Priya S.',    emoji:'👩🏾‍🍳', score:87310 },
  { rank:3, name:'Yuki T.',     emoji:'👩🏻‍🍳', score:79840 },
  { rank:4, name:'Carlos R.',   emoji:'👨🏽‍🍳', score:68200 },
  { rank:5, name:'Mama Wanjiru',emoji:'👩🏿‍🍳', score:61550 },
];

const AI_RESPONSES = {
  default_suggestions: [
    'Shakshuka — spiced eggs in tomato sauce, 25 minutes.',
    'Mujaddara — Lebanese lentils and rice, deeply satisfying.',
    'Honey Garlic Salmon — weeknight hero, 15 minutes.',
  ],
  chicken: [
    'Saffron Chicken & Rice (Persian Style) 🍋 — aromatic, one-pot, ready in 45 minutes.',
    'Lemon Herb Roast Chicken 🌿 — simple but stunning with crispy skin.',
    'Thai Basil Chicken Stir-Fry 🌶 — 15 minutes, bold flavours, great over jasmine rice.',
  ],
  keto: [
    'Garlic Butter Steak with Asparagus 🥩 — high protein, under 400 cal.',
    'Creamy Tuscan Salmon 🐟 — rich, filling, zero carbs.',
    'Cauliflower Fried Rice with Shrimp 🦐 — all the flavour, none of the carbs.',
  ],
  vegan: [
    'Coconut Chickpea Curry 🥥 — creamy, fragrant, 30 minutes.',
    'Roasted Beetroot & Lentil Salad 🫐 — earthy, satisfying, protein-rich.',
    'Mushroom & Black Bean Tacos 🌮 — smoky, hearty, crowd-pleasing.',
  ],
  budget: [
    'Pasta e Fagioli 🍝 — Italian bean soup for under $2 per serving.',
    'Spiced Red Lentil Dal 🫘 — feeds 4 for $6 total.',
    'Egg Fried Rice 🍳 — use up whatever vegetables you have.',
  ],
  kenya: [
    'White Ugali 🫓 — Kenya\'s iconic maize staple, ready in 17 minutes.',
    'Sukuma Wiki 🥬 — collard greens "pushing the week" with tomatoes and garlic.',
  ],
};
